#!/bin/bash
####### PARTE COMUM A QUALQUER TIPO DE NÓ #######
## Para restartar todos os serviços necessários depois da instalação de pacotes sem a fatídica mensagem de prompt para escolha dos serviços que devem ser reinicializados. ###
sudo sed -i 's/#$nrconf{restart} = '"'"'i'"'"';/$nrconf{restart} = '"'"'a'"'"';/g' /etc/needrestart/needrestart.conf
sudo adduser --disabled-password --gecos "" postgres
echo "postgres   ALL=NOPASSWD:    /usr/bin/pg_.* " | sudo tee -a  /etc/sudoers.d/postgres
# Adicionando repositório do PostgreSQL 
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update -y
# Alguns pacotes... #
sudo apt-get install -y vim apt-utils ufw net-tools postgresql-client-10 wget gcc make libpq-dev 